add_rules("mode.debug", "mode.release")
set_targetdir("build")
add_defines("STM8S")

after_build(function(target)
    local binOut = string.gsub(target:targetfile(), ".ihx", ".bin")
    local hexOut = string.gsub(target:targetfile(), ".ihx", ".hex")
    os.exec("sdobjcopy -I ihex ./"..target:targetfile().." -O ihex "..hexOut)
    os.exec("sdobjcopy -I ihex --output-target=binary ./"..target:targetfile().." ./"..binOut)
end)    

target("app")
    set_kind("binary")
    set_extension(".ihx")
    add_cxflags("--std-c99","--stack-auto","--noinduction","--use-non-free","--code-size 0x1800")
    add_asflags("-plosgff")
    add_ldflags("--code-loc 0x8800","--out-fmt-ihx")
    add_includedirs("app","base","include")
    add_files("base/*.c","app/*.c")